database:
  image: amsterdam/postgres
  ports:
    - "5409:5432"
  environment:
    POSTGRES_PASSWORD: insecure
    POSTGRES_DB: parkeervakken
    POSTGRES_USER: postgres

import:
  build: ./data_import
  links:
    - database:parkeervakken_db
  environment:
    PARKEERVAKKEN_DB_NAME: parkeervakken
    PARKEERVAKKEN_DB_USER: postgres
    PARKEERVAKKEN_DB_PASSWORD: insecure
    PARKEERVAKKEN_OBJECSTORE_PASSWORD: insecure
  volumes:
      - ./data:/app/data

web:
  build: ./web
  ports:
    - "8108:8000"
  links:
    - database:parkeervakken_db
  volumes:
    - $PWD/reports:/app/reports
  environment:
    SECRET_KEY: hoi
    PARKEERVAKKEN_DB_NAME: parkeervakken
    PARKEERVAKKEN_DB_USER: postgres
    PARKEERVAKKEN_DB_PASSWORD: insecure
