database:
  image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
  ports:
    - "5409:5432"
  environment:
    POSTGRES_PASSWORD: insecure

#import:
#  build: ./web
#  ports:
#    - "8101:8000"
#  links:
#    - database:database
#  volumes:
#    - $PWD/reports:/app/reports
#  environment:
#    SECRET_KEY: hoi
#    DB_NAME: postgres
#    DB_PASSWORD: insecure
