version: "3"
services:
  database:
    image: amsterdam/postgres
    ports:
      - "5409:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: parkeervakken
      POSTGRES_USER: parkeervakken
    volumes:
      - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"

  web:
    build: ./web
    ports:
      - "8130:8000"
    links:
      - database
    volumes:
      - $PWD/reports:/app/reports
    environment:
      - SECRET_KEY=insecure
      - DATABASE_NAME=parkeervakken
      - DATABASE_USER=parkeervakken
      - DATABASE_PASSWORD=insecure
      - JWT_SHARED_SECRET_KEY=insecure1234567890
      - UWSGI_HTTP=0.0.0.0:8000
      - UWSGI_MODULE=parkeervakken_api.wsgi
      - UWSGI_CALLABLE=application
      - UWSGI_MASTER=1
