version: "3"
services:
  database:
    image: amsterdam/postgres11
    ports:
      - "5409:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: parkeervakken
      POSTGRES_USER: parkeervakken
    volumes:
      - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"

  web:
    build: ./web
    ports:
      - "8130:8000"
    links:
      - database
    environment:
      - SECRET_KEY=insecure
      - DATABASE_NAME=parkeervakken
      - DATABASE_USER=parkeervakken
      - DATABASE_PASSWORD=insecure
      - DJANGO_SETTINGS_MODULE=parkeervakken_api.settings
      - UWSGI_HTTP=0.0.0.0:8000
      - UWSGI_MODULE=parkeervakken_api.wsgi
      - UWSGI_CALLABLE=application
      - UWSGI_MASTER=1
