database:
  image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
  ports:
    - "5409:5432"
  environment:
    POSTGRES_PASSWORD: insecure
    POSTGRES_DB: parkeervakken
    POSTGRES_USER: postgres

import:
  build: ./data_import
#  ports:
#    - "8101:8000"
  links:
    - database:parkeervakken_db
#  volumes:
#    - $PWD/reports:/app/reports
  environment:
    PARKEERVAKKEN_DB_NAME: parkeervakken
    PARKEERVAKKEN_DB_USER: postgres
    PARKEERVAKKEN_DB_PASSWORD: insecure
  volumes:
      - ./data:/app/data

web:
  build: ./web
  ports:
    - "8108:8000"
  links:
    - database:parkeervakken_db
  volumes:
    - $PWD/reports:/app/reports
  environment:
    SECRET_KEY: hoi
    PARKEERVAKKEN_DB_NAME: parkeervakken
    PARKEERVAKKEN_DB_USER: postgres
    PARKEERVAKKEN_DB_PASSWORD: insecure
