version: "3.0"
services:
  database:
    image: amsterdam/postgres
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: parkeervakken
      POSTGRES_DB: parkeervakken
    volumes:
      - ./backups:/tmp/backups

  importer:
    image: build.datapunt.amsterdam.nl:5000/datapunt/parkeervakken:${ENVIRONMENT}
    # build: ../../../
    links:
      - database:parkeervakken_db
    environment:
      DATABASE_NAME: parkeervakken
      DATABASE_USER: parkeervakken
      DATABASE_PASSWORD: insecure
      PARKEERVAKKEN_OBJECTSTORE_PASSWORD:
      DATAPUNT_API_URL:
    command: >
      bash -c "/deploy/import/import.sh"

