# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 13:52
from __future__ import unicode_literals

from django.db import migrations

from geo_views import migrate


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [

        migrate.ManageView(
                view_name='geo_parkeervakken',
                sql="""
SELECT
  pv.parkeer_id                                              AS id,
  pv.buurtcode                                               AS buurtcode,
  pv.stadsdeel                                               AS stadsdeel,
  pv.straatnaam                                              AS straatnaam,
  pv.aantal                                                  AS aantal,
  pv.type                                                    AS type,

  pv.e_type                                                  AS e_type,
  (CASE WHEN pv.e_type = 'E6b' THEN null ELSE pv.bord END)   AS bord,

  pv.geom                                                    AS geometrie
FROM bv.parkeervakken pv
""",
        ),

        migrate.ManageView(
                view_name='geo_parkeervakken_reserveringen',
                sql="""
SELECT
  pv.parkeer_id                                              AS id,
  pv.buurtcode                                               AS buurtcode,
  pv.stadsdeel                                               AS stadsdeel,
  pv.straatnaam                                              AS straatnaam,
  pv.aantal                                                  AS aantal,
  pv.geom                                                    AS geometrie,

  pv.e_type                                                  AS e_type,
  (CASE WHEN pv.e_type = 'E6b' THEN null ELSE pv.bord END)   AS bord,

  re.begin_datum                                             AS begin_datum,
  re.eind_datum                                              AS eind_datum,
  re.soort                                                   AS soort,
  re.opmerkingen                                             AS opmerkingen,
  re.reserverings_datum                                      AS day

FROM bv.parkeervakken pv
LEFT JOIN bv.reserveringen re
ON pv.parkeer_id_md5=re.parkeer_id_md5 and reserverings_datum=current_date
""",
        ),

    ]
