database:
  image: build.datapunt.amsterdam.nl:5000/atlas/postgres
  environment:
    POSTGRES_PASSWORD: insecure
    POSTGRES_USER: parkeervakken
    POSTGRES_DB: parkeervakken

importer:
  image: build.datapunt.amsterdam.nl:5000/datapunt/parkeervakken:${ENVIRONMENT}
  links:
    - database:parkeervakken_db
  environment:
    PARKEERVAKKEN_DB_NAME: parkeervakken
    PARKEERVAKKEN_DB_USER: parkeervakken
    PARKEERVAKKEN_DB_PASSWORD: insecure
    PARKEERVAKKEN_OS_PASSWORD:

db-backup:
  image: build.datapunt.amsterdam.nl:5000/atlas/postgres
  links:
    - database:db
  volumes:
    - ./backups:/tmp/backups
  command: >
    bash -c "echo db:5432:parkeervakken:parkeervakken:insecure > ~/.pgpass \
            && chmod 600 ~/.pgpass \
            && pg_dump --clean \
                        -Fc \
                        -U parkeervakken \
                        -h db -p 5432 \
                        parkeervakken > /tmp/backups/database.dump"

# To test restore
# docker exec -it jenkins_database_1 bash
# pg_restore -U parkeervakken -c -d parkeervakken /tmp/backups/database.dump
