version: "3.0"
services:
  database:
    image: amsterdam/postgres11
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: parkeervakken
      POSTGRES_DB: parkeervakken
    volumes:
      - ./backups:/tmp/backups

  importer:
    build:
      context: ../
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    links:
      - database:parkeervakken_db
    environment:
      DATABASE_NAME: parkeervakken
      DATABASE_USER: parkeervakken
      DATABASE_PASSWORD: insecure
      PARKEERVAKKEN_OBJECTSTORE_PASSWORD:
      DATAPUNT_API_URL:

