# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 13:52
from __future__ import unicode_literals

from django.db import migrations

from geo_views import migrate


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [

        migrate.ManageView(
                view_name='geo_parkeervakken',
                sql="""
SELECT
  pv.parkeer_id                                              AS id,
  pv.buurtcode                                               AS buurtcode,
  pv.stadsdeel                                               AS stadsdeel,
  pv.straatnaam                                              AS straatnaam,
  pv.aantal                                                  AS aantal,
  pv.type                                                    AS type,
  pv.geom                                                    AS geometrie
FROM bv.parkeervakken pv
""",
        ),

        migrate.ManageView(
                view_name='geo_parkeervakken_reserveringen',
                sql="""
SELECT
  pv.parkeer_id                                              AS id,
  pv.buurtcode                                               AS buurtcode,
  pv.stadsdeel                                               AS stadsdeel,
  pv.straatnaam                                              AS straatnaam,
  pv.aantal                                                  AS aantal,
  pv.geom                                                    AS geometrie,
  re.e_type                                                  AS e_type,
  re.bord                                                    AS bord,
  re.begin_datum                                             AS begin_datum,
  re.eind_datum                                              AS eind_datum
FROM bv.parkeervakken pv
LEFT JOIN bv.reserveringen re
ON pv.parkeer_id=re.parkeer_id and reserverings_datum=current_date
""",
        ),

    ]
